version: '3.8'

services:
  ors-app:
    build:
      context: ./
    container_name: ors-app
    image: openrouteservice/openrouteservice:v8.0.0
    ports:
      - "8080:8082"
      - "9001:9001"
    volumes:
      - ./ors-docker:/home/ors
    environment:
      REBUILD_GRAPHS: "false"
      CONTAINER_LOG_LEVEL: INFO
      XMS: 1g
      XMX: 2g
      ADDITIONAL_JAVA_OPTS: ""
